[package]
name = "rust-figlet"
version = "0.1.0"
authors = ["Shruthik Musukula <shruthik.musukula@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figlet-rs = "0.1.3"
